In [8]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [9]:
arr1=np.arange(9).reshape(3,3)

In [10]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#axis=1 goes by row
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [12]:
#axis=0 goes by column
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
ser1=Series([0,1,2],index=['T','U','V'])
ser2=Series([3,4],index=['X','Y'])

In [15]:
ser1

T    0
U    1
V    2
dtype: int64

In [16]:
ser2

X    3
Y    4
dtype: int64

In [17]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [18]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [19]:
#labelling the index
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [21]:
dframe1=DataFrame(np.random.rand(4,3),columns=['X','Y','Z'])
dframe2=DataFrame(np.random.rand(3,3),columns=['Y','Q','X']) 

In [22]:
dframe1

X         Y         Z
0  0.892357  0.632711  0.652734
1  0.334764  0.183389  0.201312
2  0.495037  0.174078  0.928291
3  0.807857  0.514353  0.013036

In [23]:
dframe2

Y         Q         X
0  0.620763  0.433185  0.399585
1  0.737816  0.687156  0.774730
2  0.914695  0.063470  0.205650

In [24]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.892357  0.632711  0.652734
1       NaN  0.334764  0.183389  0.201312
2       NaN  0.495037  0.174078  0.928291
3       NaN  0.807857  0.514353  0.013036
0  0.433185  0.399585  0.620763       NaN
1  0.687156  0.774730  0.737816       NaN
2  0.063470  0.205650  0.914695       NaN

In [25]:
#re-index the combined dataframe
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.892357  0.632711  0.652734
1       NaN  0.334764  0.183389  0.201312
2       NaN  0.495037  0.174078  0.928291
3       NaN  0.807857  0.514353  0.013036
4  0.433185  0.399585  0.620763       NaN
5  0.687156  0.774730  0.737816       NaN
6  0.063470  0.205650  0.914695       NaN