In [1]:
import numpy as np

In [2]:
my_list1=[1,2,3,4]

In [3]:
my_array1=np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [6]:
 np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [7]:
 my_array1.shape

(4,)

In [8]:
my_array1.dtype

dtype('int64')