In [1]:
import numpy as np

In [3]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 1.41178762, -0.88420157,  0.4407853 ,  0.94483576,  0.7476616 ,
        0.2927912 , -0.32934432, -1.56443133,  0.58586624,  0.541212  ])

In [7]:
B= np.random.rand(10)
B

array([ 0.37234731,  0.24101065,  0.94443382,  0.89463331,  0.21487731,
        0.12033202,  0.54005912,  0.18434024,  0.02813619,  0.57795892])

In [8]:
#binary functions
np.add(A,B)

array([ 1.78413493, -0.64319091,  1.38521912,  1.83946907,  0.96253891,
        0.41312323,  0.21071479, -1.38009109,  0.61400243,  1.11917093])

In [10]:
website = 'htpp://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True